# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HesapMakinesi(object):
    def setupUi(self, HesapMakinesi):
        HesapMakinesi.setObjectName("HesapMakinesi")
        HesapMakinesi.resize(416, 453)
        HesapMakinesi.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(HesapMakinesi)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 260, 71, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 260, 71, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 260, 71, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 180, 71, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 180, 71, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 180, 71, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 100, 71, 71))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 100, 71, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 100, 71, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 340, 71, 71))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(220, 340, 71, 71))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 340, 71, 71))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(300, 260, 71, 71))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(300, 180, 71, 71))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 100, 71, 71))
        self.pushButton_15.setObjectName("pushButton_15")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 20, 311, 71))
        self.textBrowser.setObjectName("textBrowser")
        HesapMakinesi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HesapMakinesi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        self.menukapat = QtWidgets.QMenu(self.menubar)
        self.menukapat.setObjectName("menukapat")
        HesapMakinesi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HesapMakinesi)
        self.statusbar.setObjectName("statusbar")
        HesapMakinesi.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menukapat.menuAction())

        self.retranslateUi(HesapMakinesi)
        QtCore.QMetaObject.connectSlotsByName(HesapMakinesi)

    def retranslateUi(self, HesapMakinesi):
        _translate = QtCore.QCoreApplication.translate
        HesapMakinesi.setWindowTitle(_translate("HesapMakinesi", "Hesap Makinesi"))
        self.pushButton.setText(_translate("HesapMakinesi", "7"))
        self.pushButton_2.setText(_translate("HesapMakinesi", "8"))
        self.pushButton_3.setText(_translate("HesapMakinesi", "9"))
        self.pushButton_4.setText(_translate("HesapMakinesi", "5"))
        self.pushButton_5.setText(_translate("HesapMakinesi", "4"))
        self.pushButton_6.setText(_translate("HesapMakinesi", "6"))
        self.pushButton_7.setText(_translate("HesapMakinesi", "1"))
        self.pushButton_8.setText(_translate("HesapMakinesi", "2"))
        self.pushButton_9.setText(_translate("HesapMakinesi", "3"))
        self.pushButton_10.setText(_translate("HesapMakinesi", "0"))
        self.pushButton_11.setText(_translate("HesapMakinesi", "^"))
        self.pushButton_12.setText(_translate("HesapMakinesi", "*"))
        self.pushButton_13.setText(_translate("HesapMakinesi", "-"))
        self.pushButton_14.setText(_translate("HesapMakinesi", "+"))
        self.pushButton_15.setText(_translate("HesapMakinesi", "/"))
        self.menukapat.setTitle(_translate("HesapMakinesi", "kapat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HesapMakinesi = QtWidgets.QMainWindow()
    ui = Ui_HesapMakinesi()
    ui.setupUi(HesapMakinesi)
    HesapMakinesi.show()
    sys.exit(app.exec_())
